// BROWSER
export const SET_WINDOW_RESIZE = 'SET_WINDOW_RESIZE';
export const SET_WINDOW_RESIZE_FINISHED = 'SET_WINDOW_RESIZE_FINISHED';
export const SET_WINDOW_ORIENTATION = 'SET_WINDOW_ORIENTATION';
export const SET_IS_MOBILE = 'SET_IS_MOBILE';
export const SET_ONLINE = 'SET_ONLINE';
export const SET_SCROLL = 'SET_SCROLL';
export const SET_DISABLED = 'SET_DISABLED';

// BOOK
export const FETCH_BOOK_LIST_STARTED = 'FETCH_BOOK_LIST_STARTED';
export const FETCH_BOOK_LIST_FINISHED = 'FETCH_BOOK_LIST_FINISHED';
export const UPDATE_BOOK_STARTED = 'UPDATE_BOOK_STARTED';
export const UPDATE_BOOK_FINISHED = 'UPDATE_BOOK_FINISHED';
