// BOOK
export const FETCH_BOOK_LIST_STARTED = 'FETCH_BOOK_LIST_STARTED';
export const FETCH_BOOK_LIST_FINISHED = 'FETCH_BOOK_LIST_FINISHED';
export const UPDATE_BOOK_STARTED = 'UPDATE_BOOK_STARTED';
export const UPDATE_BOOK_FINISHED = 'UPDATE_BOOK_FINISHED';
